loginStreak {
  dailyAmount: 10.0
  streakBonus {
    minutesPerWeek {
      minimum: 35
    }
  }
}
role {
  loyalist: 1.5,
  devoted: 2,
  pro: 2,
  vip: 3,
  investor: 4,
  stakeholder: 5
}
donation {
  donator: 110,
  generousDonator: 2020,
  bountifulDonator: 4200,
  nobleDonator: 6700,
  philantropist: 15000
}